### ISSUE TITLE
Intel Monterey 12.0.1  打不开

### ISSUE THREAD

**Issue by carpeventus** [wl879/wl879.github.io#1]
用了一圈还是喜欢这个APP，希望作者可以修复。

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

![image](https://user-images.githubusercontent.com/21038884/141228069-34d8e5ce-a869-4d61-aaea-43f8ba9e5fed.png)

**Comment by wl879** [comment]
你好，抱谦没有及时看到邮件，之前证书过期，软件就用不了了，经过我一拖再拖，新版本上线了，买了证书，优化又加了新功能，期望不负你的等待




下载链接：https://wl879.github.io/apps/picview/PictureView_2.0.0.dmg




如果github 访问不了，可以过几天去 https://www.macwk.com/ 搜索一下 2.0.0版，我会传上传到那






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wl879/wl879.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 上午10:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wl879/wl879.github.io] Monterey 12.0.1 打不开 (Issue #1)





 
用了一圈还是喜欢这个APP，希望作者可以修复。
 
Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
 Exception Codes: 0x0000000000000000, 0x0000000000000000
 Exception Note:  EXC_CORPSE_NOTIFY
 Termination Reason: CODESIGNING 1
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
